feature/extend the about component
JokeCam/study-tasks pull request #4
Opened 2021-12-31 10:37 UTC by JokeCam

add an additional component for the About component that adds another block of text

2022-01-04 08:53 UTC, FoZzTH requested changes

2022-01-04 08:53 UTC, FoZzTH commented on adaptive-web-page/src/components/Main/About/AdditionalParagraph/AdditionalParagraph.js
> +                <span className="additional-paragraph__text-span">Extremely Deep, Dark &#38; Difficult – </span>
зачем класс называть text-span, если он обернут в span и ты и так можешь его селектнуть?

2022-01-04 08:53 UTC, FoZzTH commented on adaptive-web-page/src/components/Main/About/AdditionalParagraph/AdditionalParagraph.less
> +        font-weight: bold;
вряд ли текст будет менять, так что можно bold через тег задать, а не через стиль

2022-01-04 08:53 UTC, FoZzTH commented on adaptive-web-page/src/components/Main/About/AdditionalParagraph/AdditionalParagraph.less
> +        color: #fff;
цвет в констанут + юзай полное название #FFFFFF, а не сокращённое

2022-01-05 12:08 UTC, FoZzTH commented
ты зря сделал так изменения. нужно было:
- изменить базовую ветку
- сделать её мерж сюда

а теперь у тебя будут конфликты, которые нужно решить

2022-01-05 12:10 UTC, JokeCam commented
> ты зря сделал так изменения. нужно было:
> 
> * изменить базовую ветку
> * сделать её мерж сюда
> 
> а теперь у тебя будут конфликты, которые нужно решить

В данном случае базовая ветка это какая?
Так я ведь не мержу пока ты не апрувнул

2022-01-05 12:13 UTC, FoZzTH commented
> 

та, в которую ты мержить будешь - базовая

2022-01-06 08:30 UTC, FoZzTH requested changes

2022-01-06 08:30 UTC, FoZzTH commented on adaptive-web-page/src/components/App.js
> +  window.addEventListener('scroll', function () {
лисенеры добавляй в useEffect + нужно их убирать, когда компонент удаляется

2022-01-06 09:47 UTC, merged