Feature/create popup component
JokeCam/study-tasks pull request #6
Opened 2022-01-03 09:53 UTC by JokeCam

create popup component to confirm user age

2022-01-04 09:02 UTC, FoZzTH requested changes

2022-01-04 09:02 UTC, FoZzTH commented on adaptive-web-page/src/components/App.js
> +
не нужный отсутп

2022-01-04 09:02 UTC, FoZzTH commented on adaptive-web-page/src/components/Popup/Popup.js
> +import Classnames from "classnames"
с маленькой буквы эта библиотека юзается

2022-01-04 09:02 UTC, FoZzTH commented on adaptive-web-page/src/components/Popup/Popup.js
> +        "popup": true,
посмотри как дополнять классы.
у тебя popup всегда будет, так что нет смысла его так создавать
https://www.npmjs.com/package/classnames

2022-01-04 09:02 UTC, FoZzTH commented on adaptive-web-page/src/components/Popup/Popup.js
> +    const [displayPopup, setDisplayPopup] = useState(true)
обычно bool переменные начинаются с is, has и подобное
лучше переменовать во что-то типа: isPopupShown

2022-01-04 09:02 UTC, FoZzTH commented on adaptive-web-page/src/components/Popup/Popup.js
> +    function closePopup() {
евенты называются с on
переименуй в onClick или что-то подобное

2022-01-04 09:02 UTC, FoZzTH commented on adaptive-web-page/src/components/Popup/Popup.less
> +.popup {
less нужно поправить в соответствии комментам раньше. тоже самое будет в других прах

2022-01-05 12:09 UTC, FoZzTH approved these changes

2022-01-05 12:09 UTC, FoZzTH commented on adaptive-web-page/src/components/App.js
>  import "./App.css"
0 точек с запятой =)

2022-01-05 12:11 UTC, JokeCam commented on adaptive-web-page/src/components/App.js
>  import "./App.css"
> 0 точек с запятой =)

:>)

2022-01-05 12:44 UTC, merged